# Generated by Django 5.2.14 on 2026-05-21 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0002_marketsearchhistory_cropwatchlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('provider', models.CharField(blank=True, default='', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Chat histories',
                'ordering': ['created_at'],
            },
        ),
    ]
