# Generated by Django 5.2.14 on 2026-06-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0005_yieldprediction_favoritescheme_voicecache'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='voicecache',
            new_name='agro_voicec_respons_f88106_idx',
            old_name='agro_voicec_respons_4bc738_idx',
        ),
        migrations.AlterField(
            model_name='farmerprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('te', 'Telugu'), ('kn', 'Kannada')], default='en', max_length=10),
        ),
    ]
